export const GET_VALUES = 'GET_VALUES';
export const GET_VALUES_SUCCESS = 'GET_VALUES_SUCCESS';
export const GET_VALUES_FAILURE = 'GET_VALUES_FAILURE';

export const GET_USER_PROJECTS = 'GET_USER_PROJECTS';
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS';
export const GET_USER_PROJECTS_FAILURE = 'GET_USER_PROJECTS_FAILURE';

export const GET_USER_VALUES = 'GET_USER_VALUES';
export const GET_USER_VALUES_SUCCESS = 'GET_USER_VALUES_SUCCESS'
export const GET_USER_VALUES_FAILURE = 'GET_USER_VALUES_FAILURE'

export const GET_USER_VALUES_AND_PROJECTS = 'GET_USER_VALUES_AND_PROJECTS';
export const GET_USER_VALUES_AND_PROJECTS_SUCCESS = 'GET_USER_VALUES_AND_PROJECTS_SUCCESS';
export const GET_USER_VALUES_AND_PROJECTS_FAILURE = 'GET_USER_VALUES_AND_PROJECTS_FAILURE';

export const GET_TOP_THREE_VALUES = 'GET_TOP_THREE_VALUES';
export const GET_TOP_THREE_VALUES_SUCCESS = 'GET_TOP_THREE_VALUES_SUCCESS'; 
export const GET_TOP_THREE_VALUES_FAILURE = 'GET_TOP_THREE_VALUES_FAILURE'; 

export const ADD_NEW_USER_VALUE = ' ADD_NEW_USER_VALUE'; 

export const ADD_NEW_USER_PROJECT = 'ADD_NEW_USER_PROJECT';
